### PR TITLE
Animation updates

### LINKED ISSUE #82: 100% CPU use forever on Firefox
In the process of setting up the client parts, I noticed that my browser (Firefox) is consistently using 100% CPU for all pages on the site no matter what I'm looking at. This makes things pretty unusable at times and makes the site seem very laggy. I dug into it a bit and found that there is a CSS animation that is continuing to be animated forever whether or not it is displayed (it's the little twirly arrow thing that you get while it's loading things). As far as I can tell, there are a couple Javascript functions that toggle a `loading` class that tells the little arrow thing to either be fully opaque or fully transparent. 

@tonysecurityforcemonitor This seems to make the site somewhat unusable in Firefox. Chrome doesn't have this problem.

### PR DESCRIPTION
**Pull request by evz**
@sam-ffctn Can you make sure I didn't clobber anything here? Thanks!

Closes #82

### CODE REVIEW

**Comment by sam-ffctn** [comment]
@evz Ya everything seems to be ok

**Comment by evz** [comment]
Huh. I'm still getting really high CPU usage in Firefox when I run these changes locally. When I was piddling around with this the other day, it seemed like merely hiding that element was not enough.

**Comment by sam-ffctn** [comment]
@evz strange, I thought I had it fixed, I'll take a look at it in the morning

**Comment by sam-ffctn** [comment]
@evz sorry about that, not sure how I missed a few things. I completely tested and had profiled it...
anyways here is the fixed version: 
url: https://ffctn.com/clients/on/sfm/M29/
zip: https://ffctn.com/clients/on/sfm/sfm-2017-04-11.tar.gz

**Comment by evz** [comment]
Cool! That seems to have done the trick. Merging.

**Comment by evz** [comment]
@tlongers I just deployed this if you want to check it out.

**Comment by tlongers** [comment]
All good - thanks @evz @sam-ffctn - the CPU the site demands in Chrome fluctuates as expected, and doesn't stick high. In Firefox (on OSX), similar.

**Pull request merged**
